config/routes.rb
Rails.application.routes.draw do
  root to: 'queries#index'
  
  resources :users do
    resources :queries
  end

  resources :user_sessions, only: [ :new, :create, :destroy ]

  get 'login'  => 'user_sessions#new'
  get 'logout' => 'user_sessions#destroy'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/query.rb
class Query < ApplicationRecord
    belongs_to :user

    def self.find_definition(query)
        %w(rubygems wordnik).each {|lib| require lib}

        Wordnik.configure do |config|
            config.api_key = '2bc43a11797607b43f40936e113939c32e5317c0cb0bc59f6'
        end

        definition =  Wordnik.word.get_definitions(query.word)
        definition_text = definition[0]['text']
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :queries
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  def index
    @queries = Query.all
    id_of_day = Query.pluck(:id).shuffle.first
    @query_of_day = Query.find(id_of_day)
  end

  def show
    @query = Query.find(params[:id])
    @definition = Query.find_definition(@query)
  end

  def new
    @query = Query.new
  end

  def create
    @query = Query.new(query_params)
    begin
      @query.definition = Query.find_definition(@query)
    rescue
      flash.alert = "#{@query.word} was not recognised"
      render new_query_path
      return
    end
    @query.save
    redirect_to queries_path
  end

  def destroy
    @query = Query.find(params[:id])
    @query.delete

    flash.notice = "#{@query.word} was deleted at #{Time.now}"

    redirect_to queries_path
  end

  def query_params
        params.require(:query).permit(:word)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

    def new
    end

    def create
        if login(params[:email], params[:password])
            redirect_back_or_to(users_path, notice: 'Logged in successfully.')
        else
            flash.now.alert = "Login failed."
            render action: :new
        end
    end

    def destroy
        logout
        redirect_to(:users, notice: 'Logged out!')
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyWord</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <%= link_to "My Word!", queries_path, class: "logo" %>
        <% if logged_in? %>
          <%= "Logged in as #{current_user.email}" %>
          <%= link_to "(logout)", logout_path %>
        <% else %>
          <%= link_to "(login)", login_path %>
        <% end %>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/queries/_form.html.erb
<%= form_for(@query) do |f| %>
  <ul>
  <% @query.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :word %><br />
    <%= f.text_field :word %>
  </p>
  <p>
    <%= f.submit "get definition" %>
  </p>
<% end %>

app/views/queries/create.html.erb
<h1>Queries#create</h1>
<p>Find me in app/views/queries/create.html.erb</p>

app/views/queries/edit.html.erb
<h1>Queries#edit</h1>
<p>Find me in app/views/queries/edit.html.erb</p>

app/views/queries/index.html.erb
<h1>My words!</h1>
<h1><%= link_to "Fill a gap, get a definition!", new_query_path %>
<h4>Word of the day:</h4>
<p><%= @query_of_day.word %></p>
<p><%= @query_of_day.definition %></p>

<ul>
    <% @queries.each do |query| %>
    <li><%= link_to query.word, query_path(query) %></li>
    <li><%= query.definition %></li>
    <li><%= link_to "Delete", query_path(query), method: :delete %></li>
    <br />
    <% end %>
</ul>

app/views/queries/new.html.erb
<h1>Find a lost word! My word, what a good idea!</h1>
<% if flash.alert %>
    <div><%= flash.alert %></div>
<% end %>
<p><%= render 'form' %></p>
<p><%= link_to "Back to list of words", queries_path %></p>

app/views/queries/show.html.erb
<h1><%= @query.word %></h1>
<p><%= @definition %></p>
<p><%= link_to "Delete", query_path(@query), method: :delete %></p>

app/views/queries/update.html.erb
<h1>Queries#update</h1>
<p>Find me in app/views/queries/update.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= form_tag user_sessions_path, method: :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email %>
    <br/>
  </div>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    <br/>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

<%= link_to 'Back', queries_path %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th>Password confirmation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.password_confirmation %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Password confirmation:</strong>
  <%= @user.password_confirmation %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>